---
title: "Migration Draft"
output: pdf_document
date: "2024-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(readxl)
library(gridExtra)
library(RColorBrewer)
options(scipen = 999)
```

Data Cleaning
```{r}
armenia_data <- read_excel("../Data/Migration Armenia.xlsx")
unemployment_data <- read_excel("../Data/Unemployment Rate.xlsx")
happiness_data <- read_excel("../Data/Happiness_Arm.xlsx")

armenia_data <- armenia_data[1:5,]

colnames(armenia_data)[5:ncol(armenia_data)] <- as.numeric(1960:2023)

armenia_data <- armenia_data %>%
  mutate(across('1960':'2023', as.numeric))

armenia_data <- armenia_data %>%
  pivot_longer(
    cols = '1960':'2023',
    names_to = "Year",
    values_to = "Value"
  )

armenia_data <- armenia_data %>%
  mutate(Year = as.numeric(sub(" \\[YR\\d{4}\\]", "", Year)))

armenia_data <- armenia_data %>%
  dplyr::select(`Country Name`, `Country Code`, Year, `Series Name`, Value) %>%
  pivot_wider(
    names_from = `Series Name`,
    values_from = Value
  )

armenia_data <- armenia_data %>%
  left_join(unemployment_data, by = "Year")


colnames(happiness_data)[1] <- "Year"


armenia_data <- armenia_data %>%
  left_join(happiness_data, by = "Year")

colnames(armenia_data) <- c("Country", "Code", "Year", "Net_migration", "GNI_PPP", "GDP_pc_PPP", "Education_Exp", "Health_Exp", "Unemployment_rate", "Happiness_rank", "Happiness_index")

independent_armenia <- armenia_data[armenia_data$Year %in% 1990:2023,]

armenia <- armenia_data
```

```{r}
b2016 <- read_excel("../Data/Boundaries2016.xlsx")
b2017 <- read_excel("../Data/Boundaries2017.xlsx")
b2018 <- read_excel("../Data/Boundaries2018.xlsx")
b2019 <- read_excel("../Data/Boundaries2019.xlsx")
b2020 <- read_excel("../Data/Boundaries2020.xlsx")
b2021 <- read_excel("../Data/Boundaries2021.xlsx")

colnames(b2016) <- c("Country of citizenship", "Arrivals", "Departures", "Net")
colnames(b2017) <- c("Country of citizenship", "Arrivals", "Departures", "Net")
colnames(b2018) <- c("Country of citizenship", "Arrivals", "Departures", "Net")
colnames(b2019) <- c("Country of citizenship", "Arrivals", "Departures", "Net")
colnames(b2020) <- c("Country of citizenship", "Arrivals", "Departures", "Net")
colnames(b2021) <- c("Country of citizenship", "Arrivals", "Departures", "Net")
b2016$Year <- 2016
b2017$Year <- 2017
b2018$Year <- 2018
b2019$Year <- 2019
b2020$Year <- 2020
b2021$Year <- 2021

b2016 <- pivot_longer(b2016,
    cols = 2:4,
    names_to = "Type",
    values_to = "Value"
  )
b2017 <- pivot_longer(b2017,
    cols = 2:4,
    names_to = "Type",
    values_to = "Value"
  )
b2018 <- pivot_longer(b2018,
    cols = 2:4,
    names_to = "Type",
    values_to = "Value"
  )
b2019 <- pivot_longer(b2019,
    cols = 2:4,
    names_to = "Type",
    values_to = "Value"
  )
b2020 <- pivot_longer(b2020,
    cols = 2:4,
    names_to = "Type",
    values_to = "Value"
  )
b2021 <- pivot_longer(b2021,
    cols = 2:4,
    names_to = "Type",
    values_to = "Value"
  )

border <- rbind(b2016, b2017)
border <- rbind(border, b2018)
border <- rbind(border, b2019)
border <- rbind(border, b2020)
border <- rbind(border, b2021)

border <- border[border$`Country of citizenship` != "Total",]

border$Armenian = ifelse(border$`Country of citizenship` == "Armenia", "Armenian", "Foreign")

summarized_border_data <- border %>%
  group_by(Year, Type) %>%
  summarize(Value = sum(Value, na.rm = TRUE))

summarized_border2_data <- border %>%
  filter(Type != "Net") %>%
  group_by(Year, Type, Armenian) %>%
  summarize(Value = sum(Value, na.rm = TRUE))

summarized_border <- summarized_border_data
summarized_border2 <- summarized_border2_data
```

```{r}
movements_data <- read_excel("../Data/Migration_Movements.xlsx")
colnames(movements_data) <- c("Reason", "Arrival", "Exit", "Balance")

move_pivot <- pivot_longer(movements_data, 
                           cols = 2:4,
                           names_to = "Type",
                           values_to = "Value")
move_pivot <- move_pivot[move_pivot$Type!="Balance",]
```

Plot preparation
```{r}
migration_plot <- ggplot(armenia, aes(x = Year, y = Net_migration))+
  geom_point()+
  geom_line()+
    geom_point(data = subset(armenia, Year == 1979), aes(x = Year, y = Net_migration), 
             color = "#E41A1C", size = 4) + 
  geom_text(data = subset(armenia, Year == 1979), aes(x = Year, y = Net_migration), 
                                                   label = "Opening of Borders", 
            vjust = 0.3, hjust = 1.1, color = "#E41A1C", size = 3)+
  geom_point(data = subset(armenia, Year == 1989), aes(x = Year, y = Net_migration), 
             color = "#377EB8", size = 4) + 
  geom_text(data = subset(armenia, Year == 1989), aes(x = Year, y = Net_migration), 
                                                   label = "Independence Movement", 
            vjust = 0, hjust = 1.1, color = "#377EB8", size = 3)+
  geom_point(data = subset(armenia, Year == 1992), aes(x = Year, y = Net_migration), 
             color = "#4DAF4A", size = 4) + 
  geom_text(data = subset(armenia, Year == 1992), aes(x = Year, y = Net_migration, 
                                                   label = "Start of Artsakh War"), 
            vjust = -1, hjust = 1.1, color = "#4DAF4A", size = 3)+
  geom_point(data = subset(armenia, Year == 1995), aes(x = Year, y = Net_migration), 
             color = "#984EA3", size = 4) + 
  geom_text(data = subset(armenia, Year == 1995), aes(x = Year, y = Net_migration, 
                                                   label = "End of Artsakh War"), 
            vjust = 1.8, hjust = -0.1, color = "#984EA3", size = 3)+
  geom_point(data = subset(armenia, Year == 2020), aes(x = Year, y = Net_migration), 
             color = "#FF7F00", size = 2) + 
  geom_text(data = subset(armenia, Year == 2020), aes(x = Year, y = Net_migration), 
                                                   label = "COVID-19 \n Artsakh War", 
            vjust = 1.7, hjust = 0.7, color = "#FF7F00", size = 3)+
  geom_point(data = subset(armenia, Year == 2022), aes(x = Year, y = Net_migration), 
             color = "#A65628", size = 2) + 
  geom_text(data = subset(armenia, Year == 2022), aes(x = Year, y = Net_migration, 
                                                   label = "Russian-Ukrainian War"), 
            vjust = -1.1, hjust = 1.1, color = "#A65628", size = 3)+
  geom_hline(yintercept = 0, alpha = 0.3)+
  geom_vline(xintercept = 1985, alpha = 0.5, color = "gold")+
  geom_vline(xintercept = 2000, alpha = 0.5, color = "gold")+
  ylim(-200000, 200000)+
  scale_x_continuous(breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  theme_minimal()+
  labs(title = "Net Migration in Armenia 1960-2023", y = "Net Migration", x = "")
```
 
```{r}
border_plot <- ggplot(summarized_border, aes(x = Year, y = Value, fill = Type)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(breaks = c(2016, 2017, 2018, 2019, 2020, 2021)) +
  theme_minimal() +
  labs(title = "Border Crossings of Armenia 2016 - 2021", y = "Number of Crossings", x = "", fill = "")
```

```{r}
border_arm_for_plot <- ggplot(summarized_border2, aes(x = Year, y = Value, fill = Type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Armenian) +
  labs(title = "Arrivals and Departures of Armenian vs Foreign Citizens Crossing Armenian Border",
       fill = "") +
  theme_classic() +
  theme(axis.title = element_blank(),
        title = element_text(size = 9)) +
  scale_x_continuous(breaks = c(2016, 2017, 2018, 2019, 2020, 2021)) +
  scale_fill_brewer(palette = "Set1")
```

```{r}
reasons_imm <- ggplot(movements_data, aes(x = "", y = Arrival, fill = Reason)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Reasons of immigration to Armenia") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5),
  legend.position = "bottom",
  legend.text = element_text(size = 6), 
  legend.title = element_text(size = 7))+
  scale_fill_brewer(palette = "Set3")
```

```{r}
reasons_em <- ggplot(movements_data, aes(x = "", y = Exit, fill = Reason)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Reasons of emigration from Armenia") +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none")+
  scale_fill_brewer(palette = "Set3")
```

```{r}
gdp_plot <- ggplot(independent_armenia, aes(x = GDP_pc_PPP, y = Net_migration, color = Year))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()+
  scale_color_continuous(high = "red", low = "blue")+
  labs(title = "Net Migration vs GDP per Capita (PPP) in Armenia", y = "Net Migration", x = "GDP per capita PPP ($)")
```

```{r}
unemp_plot <- ggplot(independent_armenia[independent_armenia$Year %in% 2001:2023,], aes(x = Unemployment_rate, y = Net_migration, color = Year))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()+
  ylim(-50000, 0)+
  scale_color_continuous(high = "red", low = "blue")+
  labs(title = "Net Migration vs Unemployment Rate in Armenia", y = "Net Migration", x = "Unemployment Rate (%)")
```

```{r}
happiness_plot <- ggplot(independent_armenia[independent_armenia$Year %in% 2013:2023,], aes(x = Happiness_index, y = Net_migration, color = Year))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()+
  ylim(-30000, 0)+
  scale_color_continuous(high = "red", low = "blue", breaks = c(2014, 2018, 2022))+
  labs(title = "Net Migration vs Happiness Index in Armenia", y = "Net Migration", x = "Happiness Index")
```

```{r}
health_plot <- ggplot(independent_armenia, aes(x = Health_Exp, y = Net_migration, color = Year))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()+
  ylim(-50000, 0)+
  scale_color_continuous(high = "red", low = "blue")+
  labs(title = "Net Migration vs Health Expenditure in Armenia", y = "Net Migration", x = "Health Expenditure (% of GDP)")
```
```{r}
edu_plot <- ggplot(independent_armenia, aes(x = Education_Exp, y = Net_migration, color = Year))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()+
  ylim(-50000, 0)+
  scale_color_continuous(high = "red", low = "blue")+
  labs(title = "Net Migration vs Education Expenditure in Armenia", y = "Net Migration", x = "Education Expenditure (% of GDP)")
```

```{r}
save(migration_plot, border_plot, border_arm_for_plot, reasons_imm, reasons_em, 
     gdp_plot, unemp_plot, happiness_plot, health_plot, edu_plot,
     file = "../Rdata_saved/migration_analysis.RData")
```
